### ISSUE TITLE
Consecutive ACC chips can greatly accelerate attackers

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#101]
I think the fix introduced for #76 can make attackers gain unexpected fantastic speed when stacking a bunch of ACC chips next to each others !

I had several unique attackers zoom past my chips towards the CPU, and i thought it was something that-randomly generated by the Endless mode, and it could be, but i've seen instances where atackers would definitely and greatly accelerate after  several consecutive ACC chips.

Maybe ACC secretly means "accelerate" 🤔😃

**Comment by Cwpute** [comment]
With some more testing i think that aceleration might be amplified by the fast-forward option !…

**Comment by ochadenas** [comment]
You are right, the attackers only ever got faster, never slower. Changed in 1.29.

However I can't confirm that it is amplified by fast forward. Or I'm too blind to see how it happens. The change in speed should be relative to the original speed (actually, it's +/- 15% now).
