### ISSUE TITLE
Level 20 bug

### ISSUE THREAD

**Issue by vertigo220** [ochadenas/cpudefense#103]
On level 20, the third coin keeps passing right through all the chips. While I realize ACC and MEM chips have no effect on them (only mentioned on the next level), I also had 1-2 each SHR and SUB chips placed that it passed through. It would rotate as it passed through them but not be destroyed/collected, allowing it to reach the core, causing damage and failure to collect the coin.

Happened on level 23 also, especially frustrating given how many tries this level took. Also levels 24, 26, and 27.

**Comment by ochadenas** [comment]
If it rotates, then it has been affected. Probably not sufficiently to be removed (coins have up to 50%  higher value than normal attackers). Just throw in one or two more levels of SHR next time.
