### ISSUE TITLE
ACC (Accumulator) Chip Clarification

### ISSUE THREAD

**Issue by vertigo220** [ochadenas/cpudefense#105]
ACC chips don't work well with spaced-out attackers, as they only have an effect when multiple attackers enter them at the same time (or close to each other?). The maximum spacing should be clarified to make players more aware of their limitations.

**Comment by ochadenas** [comment]
There is no maximum spacing. They wait for the next attacker to enter, no matter how long it takes. You can tell from the thicker frame that there is a number "inside". 

Have a look at https://github.com/ochadenas/cpudefense/wiki/ACC for more info.
