### ISSUE TITLE
Bruce Schneier Attack Strength Clarification

### ISSUE THREAD

**Issue by vertigo220** [ochadenas/cpudefense#108]
This hero needs a description of what the actual effect is. I assume it means it reduces all enemies by 1 per level or something, so upgrading it once would result in a 10 being a 01 and so forth, but it's not clear.

**Comment by ochadenas** [comment]
That's a factor that is applied to the strength. E.g. "x 0,37" means that the strength is scaled down to 37%.

Perhaps it would be clearer to change this into "- 63%".

**Comment by ochadenas** [comment]
I've changed this into "37%" (version 1.29). 

This is however inconsistent with Vaughan. So I'm not really convinced ...

**Comment by vertigo220** [comment]
Perhaps I didn't phrase this well. The real issue is just understanding what effect it is having. I like to know, before I spend any currency on anything, what it's going to do, and all it says is that it affects strength, but not what that means or by how much. So first of all, and the bigger issue, is that with TD games, strength can mean damage to the base (core in this case) or even towers (chips in this case, though this game doesn't use that mechanic). In this case, it appears it means _health_, and really that word should be used, or perhaps "size" should be used. The smaller issue is that, until buying the hero, you can't tell if it's a miniscule difference or actually significant. If I knew it would only decrease the health/size by 1, I'd rather upgrade other heroes, but if I knew it was a percentage decrease, I probably would have bought/upgraded that hero earlier.

**Comment by ochadenas** [comment]
Ah. I understand. Well, "strength" means the number that is shown on the attacker. That corresponds to _health_, if you want to. (The damage to the base is exactly 1 for all attackers.)

In fact, the mechanism is this: Each wave has a maximum strength. (Usually increasing with every new wave.) For each attacker a random (possibly fractional) number is chosen between 0 and the max strength. This number is multiplied with Schneier's effect, and then rounded down to the nearest integer.

Especially for that dreaded level 8, Schneier can make a HUGE difference ;)

**Comment by vertigo220** [comment]
What about "value?"
