### ISSUE TITLE
Heroes scrolls very slowly

### ISSUE THREAD

**Issue by vertigo220** [ochadenas/cpudefense#109]
Scrolling through the heroes to upgrade them is made difficult due to the fact it barely scrolls when swiped. While 3.5 heroes' boxes are visible on the screen at a time, swiping from the very top/bottom of the screen all the way to the other edge only scrolls them by a little under two boxes. Trying to quickly swipe repeatedly to move quickly through them doesn't work and just causes them to scroll by ~0.5-1 box at a time.

**Comment by ochadenas** [comment]
sped up hero scrolling in version 1.29

**Comment by vertigo220** [comment]
@ochadenas This is slightly better, but still very jerky. Doing a quick swipe, which in most apps smoothly scrolls by a page or more, barely scrolls more than one hero.
