### ISSUE TITLE
Isn’t imitation the sincere form of flattery? (DDoS Defender: A re-implementation of CPUdefense in Godot).

### ISSUE THREAD

**Issue by Urban-Hacker** [ochadenas/cpudefense#115]
Hello,

I've been deeply impressed by your game. Nowadays, I find myself rarely engaged with video games, as many seem overly complex or demand a significant initial commitment.  Its gradual complexity increase and the unique reset hero coins feature stand out, especially for someone like me who finds most games dauntingly complex to get into.

Given the game's open-source nature, I've been pondering how I might contribute to its development, particularly in level creation and the artistic aspects. After some reflection, I've decided to undertake a project to re-implement a version in Godot. 

![image](https://github.com/ochadenas/cpudefense/assets/92275709/fb688427-5131-4174-bd4f-950bdebe3b29)

Utilizing a game engine could lower barriers for others to design and share their levels, fostering a broader community contribution. Of course DDoS Defender is fully open source using the same license MIT.

**I have a few ideas to share:**

-  Simplify level creation for users, allowing submissions via pull requests.
-  Use icons for chips/circuits for better clarity.
-  Introduce new mechanics like a cooling fan to lower the heat instead of just relying on hero.

I hope you're open to these suggestions from someone inspired to create a related project. Looking forward to your thoughts.

Urban

**Comment by Kutabu** [comment]
Hi Urban,

I highly support your commitment! Especially the user-created levels would be a great enrichment for the game (like in Yiotros game _Antiyoy_). The endless levels have already been a big step forward in keeping the game longer interesting. But the generation of the levels varies significantly and an exciting game experience cannot always be guaranteed. The current way of creating levels via code is not practical. A level editor would be just the right thing!

I have already thought about the option of adding a cooling option to compensate the effect of the CLK chip. A fan is the obvious solution, but does not really fit in the current game logic, where chips correspond to CPU-based computer elements. I couldn't think of anything that will make sense in this way... Maybe it is an option to enable upgrading the CPU itself, i.e. to make it a clickable element and not just a target for the attackers.

I'm very curious to see what happens next!

**Comment by Urban-Hacker** [comment]
I think CPU defender does one thing very correctly. Slowly reveal more mechanics and on-board the player. It’s pleasant and you have a nice ramp up from very easy to more challenging.

sub chip -> tap to invert -> crypto coins -> hero -> etc. 

After the "hero of the informatino age" it kind of plateau because there are no new chip and the only new content is new levels. I think having an option to upgrade the CPU would make sense and maybe to make it challenging the CPU only has one type of upgrade that you can perform.

1) A Faraday cage:  this will protect the CPU from incoming bits but once destroyed cannot be rebuilt
2) A cooling fan: This dissipate the heat

This would provide two "electronically" inspired game mechanics.

**Comment by Cwpute** [comment]
What's the direction you want to take your own iteration ?
From what transpires in your words, is essentially that you want more content to linearly discover, play with and play through.

Good luck on your game, be sure to post a link to it once its made available ;)

**Comment by Urban-Hacker** [comment]
@Cwpute, Sure I can go in more details. I wanted to avoid to "spam" too much the original ticket about my own project and I will create a dedicated repository for it.

The game is called "DDoS defenders". You work for a company that defends network against distributed denial of service during the night shift (when attacks are more vicious). Attacker flood network of various companies / gov departments / etc. The hackers set the [TTL value](https://en.wikipedia.org/wiki/Time_to_live) of their packet really "high" to ensure it cross the maximum amount of nodes to reach the core.

Your job is to modify the hubs with various enhancements (eg: the subtractor, the shift / divider, the memory, etc) to avoid having packets reaching the core of your network (equivalence to the CPU).

You have access to a very simplified cyber-threat map of the city in which Missions / quest will always involve one company that you must protect and a hacking group (depending on the target / hacking group missions might be more difficult than other).

![image](https://github.com/ochadenas/cpudefense/assets/92275709/adbd8aca-6447-47b1-b9db-2498dbfa70e9)

From the initial 5 levels for the on-boarding process you are then free to choose between 1 to 3 available / unlocked mission. My goal for future improvements is that by choosing different missions you will unlock different timelines / achievements. Ideally some missions will force you to choose a path.

In the city for immersion I also want to place a store and a black market in which you can buy various upgrade for your nodes. I want to keep the idea of resetting periodically hero to enable you to unlock / progress in certain missions but I do not know yet if I will use the "hero" approach or something you can buy on the store. I like the fact that you must reset this forces you to re-think every time instead of just re-assigning coins.

I’ll also use some dark humor to explain / justify certain gameplay choice. Eg: I noticed in CPU defense the "bits" you collected in one level do not carry over. I found this odd the first time I played. In DDoS defender they do "carry" but most of them ends being split among the shareholders of the company (because they are very greedy). So you only go with the bear minimum every mission.

**Comment by Cwpute** [comment]
Fantastic ! i'd love to give some feedback once you get a prototype working :)

Mostly this sounds like a narrative overhaul with graphics improvments —i'll be most intersted in seeing the gameplay modifications you implement— but this goes a long way already towards a strong campaign, something ochadenas themselves hinted at early on, and wanted to get going. I'm sure they'll have intersting ideas to share as well !

Le 8 mars 2024 09:09:10 GMT+01:00, Urban-Hacker ***@***.***> a écrit :

**Comment by ochadenas** [comment]
Good luck for your project, and I'd like to test it once there is a prototype!

Some other remarks:

- A level editor would certainly be nice, but at the moment, there are so many suggestions for improvements, and I have not the time to do all of them ...
- This is my first project on github, and I have little to no experience on how to set up collaboration. I think that the way how to do this is via git pull requests. So new levels or code improvements can be done via committing and pushing them to the repository.
- Anyway, the wiki should be open for editing, so feel free to add pages.
- I'm a great fan of Yiotro ;)
- In the current version, there is a hero that reduces heat generation. Perhaps there could be a second to improve cooling.

**Comment by Urban-Hacker** [comment]
I created a repository for DDoS Defender, I feel like we can close this ticket (since its not really an issue). 

https://github.com/Urban-Hacker/DDoSDefenders

Please keep in mind its not ready to be played / used / tested. It’s mostly the prototype I’m building and now there are no level. Suggestions and ideas for DDoS defenders is better discussed in its own repository and @ochadenas thanks again for creating CPU Defense and not reacting "badly" after learning a random dude on internet is re-implementing your game.

I’ll probably (if @ochadenas is okay with it) create another issue / discussion when DDoS defender is ready to be played / tested by a bigger audience.

Thanks a lot for your feedback, feel free to ask me questions / suggest ideas but please do it in the proper repository to not spam this one.
