### ISSUE TITLE
1.30 endless mode now has an end?

### ISSUE THREAD

**Issue by The-JMFB** [ochadenas/cpudefense#118]
![Screenshot_20240311_072504](https://github.com/ochadenas/cpudefense/assets/39312465/aa24d5d5-727e-48d2-be22-f1596c418330)
Woke up to 1.30. I was happy to spend some crypto coins maxing out a new hero, but then I started my next level...

I don't think I'll make it to level 100 lol. What am I going to do with this? In 1.29 I had one negative chip to deal with per level at these levels. This is a bit of an escalation. Just curious if it's intentional or a bug or maybe just an oversight?

**Comment by ochadenas** [comment]
No, that is not intentional. Will have to revise the number of negative chips ...

**Comment by ochadenas** [comment]
Should be better in 1.31.

In fact, in 1.30 for each level a new negative chip / chip upgrade was added (on average). I had never thought that one would make it to level 80 or 90 ...

In 1.31, this number goes with the square root of the level, so it grows considerably slower. And besides the chip type is taken into account. One SHL now equals more than 2 NOPs.
