### ISSUE TITLE
Upgrade/Level-up MEM chips to hold more attackers

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#119]
Allow MEM chips to level up to hold several attackers: 1 at level 1, 2 at level 2, 3 at level 3 etc… they would only need be emptied when that upgraded limit is reached.
Obviously, since this is a very powerful upgrade, the price for leveling them up should be very high: 150 bits for the first level-up maybe ? then increasingly pricey.
If this still is too powerful, you could tie MEM chip max-level to hero upgrades, so that you'd have to first spend cryptocoins on upgrades, then pay a price in bits while playing the levels.

I had thought about this since a good time now, but MEM chips were already very powerful… but now that they need you to actively empty them, this idea can be considered ! The chips being able to swalow several attackers before needing a reset might even be a double-edged sword, as the player could forget their highly levelled-up chip even needs attention, and let a whole bunch of attackers slip through.

Such upgrades i thought about while reading about @The-JMFB 's forray into ultra-hard levels in Endless 80 and above. As designed, they are evidently very much fitted for end-game levels: they would serve as even more power-progression and defense potential in later levels, and provide new interesting and anticipated management choices in the form of chip level-ups of an entirely different scale.

**Comment by The-JMFB** [comment]
I'll second that suggestion - a very good option to help balance the swarm effect of later levels!

**Comment by Kutabu** [comment]
I added this to  #124, because I cannot move an issue to the discussion-board (maybe @ochadenas can).

**Comment by ochadenas** [comment]
Implemented in version 1.33 (but will surely still undergo changes in later versions)
