### ISSUE TITLE
Increase inf.price for leveling-up to ACC& chips

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#121]
I think leveling up the ACC chip to its final ACC& upgrade should be made quite more expansive.
In my game, the prices are: ACC+(10bit) > ACCv(15bit) > ACC&(37bit). In my opinion, that last level price could easily be inflated to 70bit (4 to 5 times the price of an ACCv upgrade).

An plain ACC+ is already a hugely important and chip to place down in a level, considering how cheap it is (until additional ACC chips become overly expensive), and how powerful it relatively is, halving the number of attackers passing through. ACC& is also this humongous powerhouse all later levels are built on. But you never get to see much of ACCv as you mostly ever get it as a simple first before buying an ACC& — think of it as Charmeleon, the weird midway phase you'll never stick with.
This suggestion would give more playtime with ACCv, make some levels in Turbo a bit more difficult (a wild guess, but i think that's where ACC& chips shine the most), and add more interesting choices as to what chip to upgrade and when.

**Comment by Cwpute** [comment]
As a side note, i realize the entirety of the balance suggestions i'm making are based on game-feel alone, but should probably base themselves on actual data instead. A spreadsheet of chip prices, hero upgrades, and potential damage output expected for each them, all faced with level complexion, could tremendously help analyse the difficulty curve of this hame.

**Comment by The-JMFB** [comment]
I agree with the spirit of this suggestion, but I have reservations about it in the late endless levels. After a certain point in endless, being able to OR those attackers, frequently, is the only thing that makes winning possible anymore.

I completely agree with your thinking in the normal and turbo modes, however. Depending on how the upgrade paths develop for endless, this may still be a viable option. As upgrades are currently applied, I fear the time it would take to implement enough OR ACC's would put the endless ceiling somewhere between level 40-50. With some help on the maximum starting Information, this is could still be implemented in a balanced way for those higher levels too. If the starting information cap were to increase relative to the cost of those upgrades (at higher endless levels), it could still work.

**Comment by Cwpute** [comment]
> being able to OR those attackers, frequently, is the only thing that makes winning possible anymore.

You mean, by tapping on them ? or using ACC+ chips ? or you may be mistaking OR chips for AND chips ? or i may ? who knows 🤡

> With some help on the maximum starting Information, this is could still be implemented in a balanced way for those higher levels too. If the starting information cap were to increase relative to the cost of those upgrades (at higher endless levels), it could still work.

True. Although the solution you ask for has a caveat: automatically raising the quantity of inf. you stant a harder level with would artificially flatten the difficulty.
If this really is a problem in later Endless levels, maybe we should reconsider how Hollerith's most advanced upgrades augment the quantity of starting inf. Feel free to suggest such a thing :p
Or maybe nobody was ever meant to reach Endless 100 👀 that makes for a nice round number though (but i prefer Endless 88)

**Comment by The-JMFB** [comment]
You're correct, my brain inverted OR and AND lol.

I don't mean that the information starting cap should be increased everywhere, just in the endless upgrade path (when that is added - if this suggestion were also implemented, otherwise it's fine as it is). It doesn't even have to be available until later in the endless levels, but an increased ACC cost would be pretty devastating in those later levels without some method of balancing that increased cost due to the swarms of very strong attackers in even the first few waves.

**Comment by Cwpute** [comment]
Attackers being so strong i feel is rather an oversight of how quickly their strenght progresses, because even with Schneier upgraded to its latest, attackers start to become overly strong arond Endless 20... by overly strong i mean that the first waves can't be tackled with simple SUB chips, MEM and ACC are required. 
But we digress. Maybe @ochadenas could open a discussion section for this repository so we can discuss things without them being left open like bug reports or suggestions ? 
----- Mail original -----

De: "The-JMFB" ***@***.***> 
À: "ochadenas/cpudefense" ***@***.***> 
Cc: "Cwpute" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mardi 12 Mars 2024 14:28:25 
Objet: Re: [ochadenas/cpudefense] Increase inf.price for leveling-up to ACC& chips (Issue #121) 



You're correct, my brain inverted OR and AND lol. 
I don't mean that the information starting cap should be increased everywhere, just in the endless upgrade path (when that is added - if this suggestion were also implemented, otherwise it's fine as it is). It doesn't even have to be available until later in the endless levels, but an increased ACC cost would be pretty devastating in those later levels without some method of balancing that increased cost due to the swarms of very strong attackers in even the first few waves.

**Comment by ochadenas** [comment]
Phew, quite a lot of text ;)

I have opened a discussion section. Didn't know that this existed, I'm still not really at home with gitlab.

I will provide a spread sheet for chip prices; they are quite straight forward, anyway. 

Doubtless the difficulty of the endless levels (and their progression) must still be adjusted. I think it's a kind of iteration process which will not be achieved in one version or two. However, my feeling is that the chip base/update pricing is not the right place for level fine-tuning. I would keep this independent from each other. What I mean is, let's define the basic chip value mechanism, and tweak the levels difficulty depending on it.

**Comment by ochadenas** [comment]
Price of chips and their upgrades:
https://github.com/ochadenas/cpudefense/wiki/Cost-of-Chips-and-Upgrades

**Comment by Cwpute** [comment]
> However, my feeling is that the chip base/update pricing is not the right place for level fine-tuning. I would keep this independent from each other. What I mean is, let's define the basic chip value mechanism, and tweak the levels difficulty depending on it.

This isn't about level fine-tunning: the core level progression in Normal is very good in my opinion. Yes it would need some adjustments here and there, but it's standing on its legs alright 👍 the problem really comes from Turbo and Endless, which have been added as bonus for players willing to get harder difficulty, but which difficulty have not been adjusted. Many of them are way too easy, partly because of the ACC chip i believe, and this suggestion aims at adressing this.

**Comment by ochadenas** [comment]
I'm closing this issue. Let's continue on the discussion page.
