### ISSUE TITLE
Hidden chip spots appear when app regains focus

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#122]
When you're playing an Endless level, switch to another app (the game loses focus) and switch back to the game: some chip placements spots that were not there now became visible, but they are all disconnected from the circuit wires.
![Screenshot_20240312-125518](https://github.com/ochadenas/cpudefense/assets/80604512/5691cb0a-ebfe-4759-bcd6-beacaeecc52f)
![screenshot00330](https://github.com/ochadenas/cpudefense/assets/80604512/3de8d4ea-1c4f-4a1e-939f-ba620972fa6b)
As you can see, the background also changes, just a minor bug.

**Comment by Cwpute** [comment]
Also minor bug: apparently the game forgets the language you were playing the game with, consider both toasters in my screenshots say the same thing, respectively in french… then english!

**Comment by Cwpute** [comment]
Just found another special case:
![Screenshot_20240312-140219](https://github.com/ochadenas/cpudefense/assets/80604512/7b6b9665-2789-4759-b10c-e18e67b98c9b)
A second CPU revealed itself as well, and chip spots appeared on the copper lane, seemingly connected to the circuit, but when attackers get past them, they don't interact and let them through (portrayed here by the last chip spot before the CPU).

**Comment by ochadenas** [comment]
I hope that the bug with the hidden isolated slots has been fixed in 3.31. Please have a look once it gets available ...

As for the toasts, I have no idea. You are right, I can reproduce this. These toasts are a system functionality, this is quite opaque to me. Maybe this is even an Android issue.
