### ISSUE TITLE
ACC sell price currently independent from ACC chips quantity on the board

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#123]
While the buying price of ACC chips raise for each new one added to the board, their resell price never rise.
This can lead to signifant investment losses when selling an ACC chips after so many others were installed, regardless how the level at which you upgraded Tramiel (and not Tamriel, as i keep writing it).

I'm not sure this is intended behavior, hence this issue creation, and-not sure either if changing the curent

**Comment by ochadenas** [comment]
No, that is a bug. Thanks for mentioning it.

**Comment by ochadenas** [comment]
> and not Tamriel, as i keep writing it

that sounds Elvish, somehow ;) 

Issue fixed in 3.32.
