### ISSUE TITLE
1.31 select level

### ISSUE THREAD

**Issue by The-JMFB** [ochadenas/cpudefense#125]
I don't recall where I read you mention changing this, but I could swear I read it. In endless, I can now select up to level 29 (instead of only 28), but no higher. Not that big of an issue... I can get back to 93 by playing through again, just sharing.

![Screenshot_20240313_115718](https://github.com/ochadenas/cpudefense/assets/39312465/3f18c954-59fa-44fc-a20d-0479a9608f8c)

**Comment by ochadenas** [comment]
Should be fixed (really this time!) in 1.32.
