### ISSUE TITLE
game crashes Ehen loading endless level game

### ISSUE THREAD

**Issue by Tinsus** [ochadenas/cpudefense#128]
Since the latest update the game crashes whenever i want to load a endless game, normal and turbo works find, only endless crashes right after Pressung the LOS button (GO in english). It makes no differance if I try to load the first or last or whatecer weithin endless game it crashes. After starting the app and try to load an endless level - in the first try the game exists to the Main Menü, with the second try it crashes completly to my home screen.

**Comment by Kutabu** [comment]
I had temporary the same problem, but I went into a blackscreen (level did not load). Have you tried to stop the app in android and start it again? This worked for me.

**Comment by Tinsus** [comment]
Disable, reload the level and reenable the Option "keep endless level" fixed it for me.

May some changes in the structure how the level is stored causes the problem?


Am 15. März 2024 10:44:42 UTC schrieb Kutabu ***@***.***>:

**Comment by ochadenas** [comment]
I think this is due to bugs in level creation, so the (temporary) solution is just what you have done: Create a new one.

Most of the problems should be solved in 1.31 or 1.32, so please give it another try once a new version is available.
