### ISSUE TITLE
Crashes on Nougat

### ISSUE THREAD

**Issue by PerspexSphinx** [ochadenas/cpudefense#131]
Crashs for me under android 7.0 (nougat)…
my phone specs:
Qualcomm Snapdragon 1.4 GHz Octa-Core
armeabi-v7a
1920x1080 pixels (386ppi)

**Comment by ochadenas** [comment]
Could you
- describe what you were doing
- specify the version you are using
- try with the most recent version available (1.31, or 1.32 when it becomes available)?

**Comment by PerspexSphinx** [comment]
Version 1.34…
When resume game…
Play selected level.…
Still crashes under Android Nougat with armeabi-v7a but seems to work on my Arm64-v8a tablet with Nougat and a 800 × 1280 screen size.

**Comment by PerspexSphinx** [comment]
version 1.35
Android Nougat - armeabi-v7a
Got up to level 6 but when I try to hire a hero on level 7 it crashes.
I have disabled the background, have show attackers in range swiched on and I m using large objects.

**Comment by ochadenas** [comment]
I suppose that has been fixed. I'm closing the issue. Please open a new one if there are more crashes.
