### ISSUE TITLE
Endless mode level selection screen forgets how many cryptocoins were won

### ISSUE THREAD

**Issue by klaviartur** [ochadenas/cpudefense#145]
When you restart a previously won level in endless mode the cryptocoin won count is reset
if you don't finish the level a second time the "x of 3 coins won" line is missing completely, which is extra annoying in combination with #144 .
If you do finish it a second time, it says "0 of 3 coins won"

I understand the coins work differently in endless mode when compared to mission mode anyway as you cannot come back for a lost coin later.

So the obvious thing here would be to display (and remember) the amount of coins won in total in that level (including attacker coins).
When the level is repeated, the coins won count can be increased.

**Comment by ochadenas** [comment]
Has been fixed in 1.34. (Hopefully, at least.)
