### ISSUE TITLE
Erratic attacker movement

### ISSUE THREAD

**Issue by klaviartur** [ochadenas/cpudefense#155]
Some attackers move erratically and do not interact with any chips:

https://github.com/ochadenas/cpudefense/assets/80008286/b5230eba-7e39-44e5-96a8-143a10612d2e

Some of them just disappear and others jump to regular movement when game is brought to background and back to foreground.

Endless mode lvl 111, v1.35

**Comment by Mortis03** [comment]
I've seen this time to time.  Usually after unpausing. I just regen the level

**Comment by ochadenas** [comment]
This is probably the same bug as in issue #158. The attackers "forget" which track they are on, and start again at the entry point.

Please try again in 1.37.

**Comment by Cwpute** [comment]
Tried with 1.45 and had the same issue. It happens consistently on the same level after several retries. Please reopen.
