### ISSUE TITLE
level 100 displayed as 00

### ISSUE THREAD

**Issue by oliItick** [ochadenas/cpudefense#157]
At homepage, when finished level 100, it displays that the last level is 00 (and next one is 101)
See screenshot

![Screenshot_2024-05-17-20-36-12-306_de chadenas cpudefense](https://github.com/ochadenas/cpudefense/assets/157179701/70087d8e-fdf7-414e-bf40-d5a2fef434ae)

**Comment by ochadenas** [comment]
Changed the level indicator to 4 digits, so this will work correctly until stage 9999. 

If you ever reach that level, you definitely have too much time.
