### ISSUE TITLE
Unable to activate chips 

### ISSUE THREAD

**Issue by sdcaulley** [ochadenas/cpudefense#160]
I am unable to click on any chips after the first one to activate them. 

Version 1.36
Lenovo Tab P11 Pro
Android 11

**Comment by ochadenas** [comment]
Could you give some additional details? Which kind of chips, and what are you exactly trying to do? Maybe provide a screenshot.

**Comment by sdcaulley** [comment]
https://github.com/user-attachments/assets/29538b6d-da93-427b-b43f-542c44c78dee

**Comment by ochadenas** [comment]
A SUB chip costs 8 bit. Just destroy a few more attackers, and you'll be able to buy the next one.

**Comment by sdcaulley** [comment]
Thank you! I missed that part.
