### ISSUE TITLE
What do resistors do? 

### ISSUE THREAD

**Issue by StrikerTwo** [ochadenas/cpudefense#162]
Just stumbled across the R chip type, but I cannot tell what it does (path probability? Attacker speed?) and it's not documented anywhere that I could find.

**Comment by ochadenas** [comment]
They are introduced in level 32 (normal mode). They have a temporary effect on the attackers' speed.

**Comment by ochadenas** [comment]
Added a wiki page: https://github.com/ochadenas/cpudefense/wiki/RES
