### ISSUE TITLE
Hero's ability in not activated until restarting level two times

### ISSUE THREAD

**Issue by Lik-the-Fluffin** [ochadenas/cpudefense#163]
I didn't have any issues until endless 5. Now if I buy some heroes and start level their abilities won't work, selling heroes won't stop them from working.
To update heroes I need:
- buy needed hero
- start level, then exit level
- enter hero shop second time and press "begin stage".

Only then game will update which abilities should be activated.

**Comment by ochadenas** [comment]
You're right. I'll have to investigate this.

**Comment by ochadenas** [comment]
The bug is worse than feared. Also the availabilty of chips, heroes etc. in the "normal" level series was delayed; in 1.36 they become active only at the end of a stage, not at the beginning.

Fixed that now. Should be ok in 1.38.
