### ISSUE TITLE
Going to main menu and then resuming causes mems to "fill up"

### ISSUE THREAD

**Issue by Mortis03** [ochadenas/cpudefense#167]
Started with v1.38. I am on stage 400+. Not sure if it does these issues on lower stages.

It also give extra money.

When you return to main menu and then resume game, mem chip slots fill up.    When you tap to free a slot, it stays filled.  Eventually if you tap enough, the slots will empty.  Its almost like it "forgets" they have been tapped before.

**Comment by ochadenas** [comment]
You're right. If going back to the main menu, the chip forgets that it is in its cool down phase, and the number within the chip again occupies the slot. That is probably a side effect of the fix for issue #120.

Will try to change this.
