### ISSUE TITLE
missing UI elements after locking screen

### ISSUE THREAD

**Issue by johndh** [ochadenas/cpudefense#17]
After locking the screen and unlocking it, UI elements like data and coins are missing from the bottom, or bits will be smaller than usual.

![Screenshot_20230312-120644](https://user-images.githubusercontent.com/692397/224563207-45636132-4cb6-418f-8594-4911726a7a35.png)
![Screenshot_20230312-125439](https://user-images.githubusercontent.com/692397/224563210-9ed0be94-a1cb-44cb-8184-111d1e3d715f.png)

Current F-Droid version

**Comment by ochadenas** [comment]
I'll try to fix that.

Element size needs some corrections anyway, the size is too small on displays with high resolution.

**Comment by ochadenas** [comment]
The problem should no longer persist in version 1.15. 

After locking (or switching to another app) the game returns to the welcome screen. From there, you can use "Resume game".

Also game element sizes have been fixed.
