### ISSUE TITLE
[1.39]The spoiler screen was a bit buggy for me

### ISSUE THREAD

**Issue by sere3925sere** [ochadenas/cpudefense#173]
The "choose a hero to leave to rest" screen was buggy for me, overlapped "x coins got" and hero portrait made things hard to see. Should've screenshotd it.

**Comment by ochadenas** [comment]
Yes, please share a screenshot.

**Comment by sere3925sere** [comment]
I will once I get the situation like this again.

**Comment by ochadenas** [comment]
In 1.45, this screen has been reworked. The "hero selection" part can be scrolled if it doesn't fit on the screen. This should solve your problem.
