### ISSUE TITLE
[1.40] screen "grant leave to hero" bugged?

### ISSUE THREAD

**Issue by torbium** [ochadenas/cpudefense#177]
I'm on endless 16 right now, and for the first time asked to grant leave to a hero. The selection menu in the center of the screen doesn't immediately show up. When I then "minimize" the application and then "maximize" it again, the selection menu shows up correctly. (I don't know the technical terms for these. Minimize = tapping the circle on the bottom center, Maximize = tapping the square on the bottom right to see the app again)
I'm using a Google Pixel 6a with the standard Android 14. Let me know if there is more information needed.
![Screenshot_20240819-065609](https://github.com/user-attachments/assets/88c26ea8-3045-4331-98e2-146a15ed1274)

**Comment by gustavi** [comment]
Thanks @torbium for the trick! I was stuck to this step and I was going to open an issue right now.

**Comment by ochadenas** [comment]
Thanks for the report. I'll have a look ...

> Let me know if there is more information needed.

Perhaps just how you got there in the first place. I assume you finished level 15 and then just continued to 16?

**Comment by gustavi** [comment]
> Perhaps just how you got there in the first place. I assume you finished level 15 and then just continued to 16?

Yes, it's my case.

**Comment by floasp** [comment]
I have the same issue at level 20. When starting the level from the "select level" menu and also coming from the previous level. 

"Minimizing" and "maximizing" the app shows the heroes correctly.

**Comment by torbium** [comment]
It doesn't matter which way I use to start the level. From the main menu, from the "select level" menu, or from finishing level 15. The screenshot in my original post was from the main menu or from the "select level" menu. When finishing level 15, I do get the green text at the bottom "Stage cleared. Next stage: 16", like I would from defeating other levels. So everything seems to be fine, just the selection menu is not showing up.
![Screenshot_20240819-170733](https://github.com/user-attachments/assets/ff60f96e-b7d0-44a9-8c9b-b3d3e243491a)

**Comment by ACsediment** [comment]
I am facing the same issue, and it doesn't matter how you start the level. I'm guessing this might have something to do with window redraw?

I've tested a few method to fix this:
- minimise the app and reopen: work✅ 
- Switching to a different window and back: work✅ 
- enter "Recent apps" view, and back (do not switch to a different window): work ✅ 
- switch to "Split Screen" mode and back: looks like the window get redrawed, but it doesn't work ❌ 
- switch to "picture-in-picture" mode: heros showed up✅ but will break the layout like a missing CSS
- scroll down notification center and back: doesn't work❌ 

v 1.40 running on Android 14

**Comment by Saxodwarf** [comment]
Hi there,
I am facing the same issue on version 1.41 on android 8 (I know, old version...).

On version 1.40 I could use the workarounds described around to bypass the issue, but since the upgrade it stays stuck.
Maybe it has to do with the "Fixed some problems when returning after switching apps" bug fix from version 1.41

Anyway, I just saw in the release note for version 1.42 that there is a bug fix that might be related to that issue, so I'll wait for the update to be available in F-Droid

Thanks for the great game!

**Comment by Saxodwarf** [comment]
Indeed solved with version 1.42!

**Comment by ochadenas** [comment]
thanks for the feedback! 

Closing the issue. Please open a new one it there are still problems.
