### ISSUE TITLE
[1.42] Make it possible to reset endless mode

### ISSUE THREAD

**Issue by floasp** [ochadenas/cpudefense#181]
It would be nice to be able to reset the progress in the endless mode. So I can restart it without also resetting all the other levels.

I needed to reset it, because i was stuck in level 38 without a win registering. (like #151 and #153) 

I reset everything and will see if it works now.

**Comment by Cwpute** [comment]
Alternatively when faced with a bug like that, you can uncheck the option that remembers endless levels. This will regenerate a new level each time you retry it.

**Comment by ochadenas** [comment]
The possibility to reset only the endless levels has been introduced in 1.47.
