### ISSUE TITLE
[1.42] No coins earned in endless mode

### ISSUE THREAD

**Issue by floasp** [ochadenas/cpudefense#182]
I restarted the game (as I mentioned in #181) but I don't earn any coins in endless mode anymore. I'm at level 7 now and only got one moving coin and no other coins, despite finishing the levels with all lives left.

**Comment by ochadenas** [comment]
fixed in version 1.48. There was indeed a problem with the coins for "endless", once the game had been reset.

The coins should now appear also on the levels already played.
