### ISSUE TITLE
[1.44] Update to 1.44 reset my game progress

### ISSUE THREAD

**Issue by floasp** [ochadenas/cpudefense#184]
When I opened the App after updating from 1.43 to 1.44 my endless mode progress was reset. On the main menu it still says I'm on level 37 but I can't resume it. I closed the app and restarted it and then the normal and turbo mode were also reset. 

I don't know if it's intended, but considering there is a new progress saving system, it might be buggy. At least the transition part from the previous saving system.

**Comment by floasp** [comment]
I just realized that just the level progress was reset, but the heroes are all still there and at the same level as before.

**Comment by ochadenas** [comment]
no, that is not intended.

The "level selection" screen is also empty?

**Comment by floasp** [comment]
Yes, all modes are unlocked but only the first level is visible on each mode.

**Comment by Dimethylebutane** [comment]
Same for me, only first level available in the select level menu and cannot resume game (lvl 29 turbo). 
I replayed up to lvl 6 and Heroes level has not been reset.

**Comment by floasp** [comment]
I think 1.46 mostly fixed it. 

I reinstalled 1.43, played till level 8, updated to 1.46 and the levels did not reset. I haven't tried if it keeps the turbo or endless mode too yet. Would've taken too long.

But the "Resume Game" Button does not work immediately after the update. After playing a level it works again.

**Comment by ochadenas** [comment]
Thank you for the feedback! If that's okay now, I am quite confident that the other modes will work, too.
