### ISSUE TITLE
F-Droid reproducible build failed

### ISSUE THREAD

**Issue by linsui** [ochadenas/cpudefense#188]
https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8538577591

Could you please make sure the apk is built from the tag? Or just remove the META-INF/version-control-info.textproto file. See https://f-droid.org/en/docs/Reproducible_Builds/#vcs-info. Thanks!

**Comment by ochadenas** [comment]
Honestly, it's a complete mystery to me what is compared to what in the build process. 

For me, I'm absolutely sure that the binaries correspond exactly to the committed version. But actually, the commit is often (not always, though) off by one. So obviously the build process is comparing something different from what I think.

> Or just remove the META-INF/version-control-info.textproto file. See https://f-droid.org/en/docs/Reproducible_Builds/#vcs-info.

Done that in the latest build (version 1.50), and that seems to work. Thanks!
