### ISSUE TITLE
[1.49] Pause state lost on Background-Foreground-Cycle

### ISSUE THREAD

**Issue by klaviartur** [ochadenas/cpudefense#191]
In any level the pause state is lost when returning to foreground. Attackers start moving, but pause button is not updated. You have to tap it twice to re-pause.

This is even worse when level has ended and you are in the between-levels-screen. If you cycle to background and foreground, game returns to the finished level, no attackers come, but info counter increases. Only way is exit to main menu.

**Comment by ochadenas** [comment]
This one was already fixed in 1.49. The pause state now is kept when changing between apps. At least, I can no longer reproduce the behaviour that you describe.

**Comment by klaviartur** [comment]
I'm  quite sure, it was on 1.49, that the problem occurred, but as it doesn't occur anymore now on 1.50, there is no relevance to this and therefore no need to argue ;)

Thanks for your work
