### ISSUE TITLE
[1.49] Hero reset ignores hidden heroes

### ISSUE THREAD

**Issue by klaviartur** [ochadenas/cpudefense#196]
Example:

1. upgrade Turing to level 5, so Wiener becomes available
2. upgade Wiener
3. downgrade Turing, so Wiener becomes unavailable
4. Hit reset
5. Upgrade Turing to level 5

Wiener is still upgraded

**Comment by ochadenas** [comment]
You are right, and what's even worse: Wiener's effect did still apply, even when the hero is hidden.

Changed this in version 1.51: A hero that is hired still remains active and visible, even if the prerequsites are no longer met. This also fixes the problem mentioned here.

This will allow, however, to purchase and upgrade Turing, then Wiener, then downgrade Turing, and Wiener still stays active. Let's
