### ISSUE TITLE
Main menu button broken 1.48 fdroid

### ISSUE THREAD

**Issue by capsicumw** [ochadenas/cpudefense#198]
On the main menu with buttons: 
PLAY LEVEL n
SELECT LEVEL
INFO
SETTINGS
QUIT

The top button (PLAY LEVEL n) is completely non-responsive, that top button is also non-responsive when displaying "RESUME GAME". 
The current workaround is to use the "SELECT LEVEL" sub-menu, but this starts a new round rather than resuming.
v1.48 on Android 13, Samsung OneUI 5.1, downloaded from fdroid (This is the latest version on fdroid.)

**Comment by carlosjeurissen** [comment]
@capsicumw v1.50 should already be available via f-droid. Try opening this url via f-droid:
https://f-droid.org/packages/de.chadenas.cpudefense/

It should probably feature an "update" button.

**Comment by capsicumw** [comment]
@carlosjeurissen Thanks it looks like I had an fdroid issue. Set to check updates only every two weeks, and even after changing that it also needed a phone restart to shake them loose.

**Comment by ochadenas** [comment]
thanks to both of you for your feedback!
