### ISSUE TITLE
level 24 stop waves

### ISSUE THREAD

**Issue by vivienprouvot** [ochadenas/cpudefense#21]
When I'm playing the 24th level, waves get stuck and no ennemies arrive anymore. 
Happened to me once wave 3,  few times wave 4 and once wave 5
I have to return to the menu and resume and the waves start again.

**Comment by juleskers** [comment]
I have had the same problem (next wave doesn't start), with the same workaround (return to me u, the "resume play") in multiple level, and I'm only at level 8.

**Comment by ochadenas** [comment]
I was not able to reproduce this. Maybe this has been fixed meanwhile "by accident". If the problem persists, please re-open an issue.
