### ISSUE TITLE
My virus scanner says there's a trojan

### ISSUE THREAD

**Issue by aidas0Baranauskas** [ochadenas/cpudefense#22]
Even if there isn't, the mere warning of one is definitely an issue as folk will be reluctant to install it

**Comment by ochadenas** [comment]
Which scanner is this?

I don't know what to do about this. Normally, one has little insight (or influence) on how these virus scanners work. I think that by pure coincidence, somewhere in the byte code there is a sequence that corresponds to a pattern in the scanner's signature list and triggers the virus warning.

I think you cannot avoid this. Just hope that the next version will have a different byte code that will not be recognized by the scanner.

**Comment by ochadenas** [comment]
I'm closing this issue, because there is nothing I can do about this.
