### ISSUE TITLE
Abbreviate large currency counts as KB

### ISSUE THREAD

**Issue by invinciblespeed** [ochadenas/cpudefense#23]
In the current game version, acquiring a large number of bits will cause the displayed currency to condense into B, but these bytes do not appear to condense further.
In a round of level 16, I was able to reach 3237B, which I feel should instead display as 3KB.

**Comment by ochadenas** [comment]
the current code switches to KiB when the score reaches 10.000 bytes, which may be way too high ... Changing the threshold to 1.000 bytes.

I've never had a score that high, so I never noticed ;)

**Comment by ochadenas** [comment]
fixed in version 1.16
