### ISSUE TITLE
Cryptocoins don't reset to correct count

### ISSUE THREAD

**Issue by Pugz4Life** [ochadenas/cpudefense#24]
Sometimes cryptocoins reset to an amount smaller than what was actually spent.
Seems to be inconsistent but happens often.
Seems to occur more often with multiple upgrades selected.

**Comment by cloudwindy** [comment]
Same problem here. @ochadenas

**Comment by ochadenas** [comment]
corrected a dubious calculation, but I'm not quite sure if that fixes the problem. Will have to take a closer look.

**Comment by ochadenas** [comment]
Should be fixed in 1.16.
