### ISSUE TITLE
Very low framerate

### ISSUE THREAD

**Issue by Saltermelon** [ochadenas/cpudefense#26]
Game seems to run at a low framerate when not sped up, and it makes it difficult to reliably flip the bits.

**Comment by ochadenas** [comment]
The app now updates the background less often. Please try again with version 1.16.

**Comment by JinPlanter** [comment]
Installed on android and the numbers looks choppy on default speed,

not sure what engine this was made in but you might want to use interpolation for the movement of the bits, perhaps that might fix the 'framerate' issue

here's a 5min example from Garbaj: 
[Fixing Jittery Movement In Godot](https://www.youtube.com/watch?v=pqrD3B75yKo)

**Comment by Itja** [comment]
I am having the same experience on Android. Tapping on the invading bits to flip them works only half of the time for me and it all seems really low fps, except when the speedup is active.

**Comment by ochadenas** [comment]
Version 1.21: The game now runs at a fixed (and, in most cases, higher) frame rate. Tried it in the emulator with different screen resolutions, and it runs much smoother now, even on large-sized displays.
