### ISSUE TITLE
Heroes screen "cost:" chopped of by frame. 

### ISSUE THREAD

**Issue by juleskers** [ochadenas/cpudefense#28]
Thank you for making this! I find it pleasant to play! 

In the heroes screen, on my phone, the "cost:" is usually unreadable.
the number dissappears under the box edge, depending on how many letters are in front of it (upgrade effect description).

I would have attached a screenshot, but per #20, I cannot currently reach the Heroes-screen to take a screenshot.

I'm running a de-googled OS (e/OS on Fairphone 3), so perhaps my phone is using a non-default font?

**Comment by ochadenas** [comment]
you're right, I have problems reading the cost, too. Must think of a better way to display this.

**Comment by ochadenas** [comment]
changed in version 1.20:
long-tap on the hero card shows details on the upgrade effect, including cost.
Also, the cost in coins is now equal to the current hero's level, making it easy to guess.

**Comment by ochadenas** [comment]
Should be resolved in 1.20.
