### ISSUE TITLE
Idea: "retry" button on "failed to clear stage" screen. 

### ISSUE THREAD

**Issue by juleskers** [ochadenas/cpudefense#29]
Level 8 is continuing to kick my behind, so much so, that the repetitiveness of the failed-screen > main menu > play level 8 is starting to annoy me.

I'm so eager to try again, that tge extraclick bothers me.
I would like to see a "try stage 8 again"-button directly on the lose-screen ("failed to clear stage").

For that matter, I would also like this retry-button on the *win* screen, so I can retry other levels faster if I survive them, but not with perfect score (for example, missed bonus coin on level 7, or not all lives/coins on other levels.)

Brainstorming for button text label:
- retry
- replay (may confuse with "show video of what you just did" ) 
- retry stage
- play again (compare "next level") 
- retry stage <number>
- other ideas?

**Comment by ochadenas** [comment]
In level 8, the maximum value of the attackers is 2, so you won't need anything more than SUB 3.

Just place SUB chips in the two slots in the central line and upgrade them whenever it is possible. Having Alan Turing definitely helps.

**Comment by ochadenas** [comment]
Added a "retry" button.

**Comment by juleskers** [comment]
Thank you for the button! 
Also for strategy tips, I'll try that next.

The problem I currently see, is that I have spread my coins over all heroes, so I don't start with enough "information" to instantly buy 2 SUB-chips in the beginning. 


That again means I need to perfectly manually-tap the first few attackers to invert them, but even then, a few of those first attackers are 10/2, so I need a perfect "tap > sub > lucky second sub" or lose a life.
I *think* I have seen a couple of the attackers go straight for the CPU, without looping, which feels really harsh.

The other problem I run into is that, once I have enough info to buy a second chip, the slot I want to buy (middle left) has sooo many attackers in it, that I have trouble triggering the buy-menu > buy Sub, without accidentally tapping/inverting an attacker, which cancels the buy menu.
in the frustrating time this takes me, I usually lose another life or two.

This is also why I think #20 is so important. Without that, I cannot Re-spec my heroes to maximise starting budget. (or at least, not without repeating level 7 until I ace it again for the bonus coin, which is starting to grate on my nerves)

All complaining aside, the fact that your game is getting me so frustrated, also shows that it is emotionally engaging me. That's a good thing! ❤️

**Comment by ochadenas** [comment]
Thanks for your feedback! I have not implemented all of the proposed changes yet, this will take some time. There have been quite some changes anyway, so I'm publishing a new release in the meanwhile, even if not everything is done.

**Comment by ochadenas** [comment]
Retry button added (v1.18, and again in v1.20)
