### ISSUE TITLE
Resetting heroes lost all coins

### ISSUE THREAD

**Issue by juleskers** [ochadenas/cpudefense#30]
I finally survived level 8 🎉 , and earned two coins.
I entered the heroes screen with my two new coins, and hit "reset all" to Re-spec my heroes.
total coins after reset: **still 2** 🤯

The game just ate 8 of my coins! 😠

I have reset my heroes before, and got (all?) my spent coins back. 
If it's intentional that coins are lost, this should be mentioned in the upgrade text..
"are you sure you want to reset all heroes? **coins won't be refunded**" (or something like that)

If it is _not_ intentional, this is a ragequit-inducing bug. 
I just spent three evenings playing this game, and lost effectively all the gains of those three evenings. I am very frustrated right now.

Thank you for listening, and I appreciate how well you are responding to all my issue reports.
I hope writing down my experiences helps you understand how others play the game (basically, playtest report 👼)

**Comment by ochadenas** [comment]
I hope this bug is fixed. If you want to give it a try, get the package from the releases section here on github. 

I'm publishing it on f-droid, too, but it'll take a week or so before it appears there.

**Comment by juleskers** [comment]
Cool!
I'll wait for the FDroid release then.


Github tip: if you include a line in your commit message that references the issue number, github will automatically create a link here.

Example Commit message.
> fix #30: coins were not refunded when resetting heroes 

("fixes #30", "closes #30" will even automatically close the issue as "resolved") 

Or, if you don't want to close. 
> hopefully fix bug that coins were not refunded, see #30“

**Comment by ochadenas** [comment]
version 1.18 is published, I'm closing the issue.
