### ISSUE TITLE
More button options

### ISSUE THREAD

**Issue by Dacid99** [ochadenas/cpudefense#31]
A retry button in the game itself would be good so if one is unhappy with their performance, it is possible to get a quick new try without having to either fail first or move to main menu.
Additionally the pause and speedup buttons inside the game could ideally be a bit larger (around 2x as large).
Also accessing the heroes directly from the main menu would be great.

I really enjoy this game, thank you for your great work!

**Comment by ochadenas** [comment]
made the button 50% bigger. Seems really quite big to me ...

**Comment by Dacid99** [comment]
Can you please show a picture? I felt like they were quite small originally, but maybe thats just my sausage fingers xD

**Comment by ochadenas** [comment]
![Screenshot_20230929_195636](https://github.com/ochadenas/cpudefense/assets/103358290/f4d5fc55-84fc-4315-b845-d364c9f130b5)
![Screenshot_20230929_195416](https://github.com/ochadenas/cpudefense/assets/103358290/af2edef2-1b23-4ea9-b580-2ebcf74fdb36)

Screen shots using two different screen resolutions. The problem with the  Pixel 4 SL (first screen shot) is that its display is much higher than wide, and that sort of kills the whole size calculation.

**Comment by Samurai1201** [comment]
Ok i see the problem. Probably making the button size adjustable in settings would be the best but also most time-consuming solution. 
Can we maybe settle for a 25% increase?

**Comment by ochadenas** [comment]
No, that's ok. In V1.20 there is now a switch in "settings".

And I've added a new button that allows replay of the level.

**Comment by Samurai1201** [comment]
Thank you very much, i appreciate it. Keep up the good work!
