### ISSUE TITLE
Just a Thank You!

### ISSUE THREAD

**Issue by davidbaunach** [ochadenas/cpudefense#34]
Not really an issue, just wanted to say thanks for such an awesome game! Burned through it in a few days and absolutely loved it! Is there any way to throw a few dollars at the contributes in thanks? Crypto address, Patreon, or anything like that?

**Comment by ochadenas** [comment]
Thanks a lot for your comment! Glad that you like the game. 

No, I'm afraid there is no possibility of leaving money. At least at the moment, maybe I should think about it ... no, seriously: This is just a hobby project, and if people have fun playing, I'm really happy. And besides, I have played a lot of games in my life that someone has provided for free, so I feel I could give something in return.

**Comment by DavidBurela** [comment]
+1 to this. Just discovered it on F-droid, and have been enjoying playing through the levels. Thanks for creating it.
