### ISSUE TITLE
Rename START NEW GAME to RESET GAME and maybe move it to the Settings 

### ISSUE THREAD

**Issue by osjasmine** [ochadenas/cpudefense#35]
I think the start new game option gives the impression that it will restart the current level and not the whole game. Also the option is probably not used very often so maybe it should be moved over to the settings.

I ve twice accidentally pressed start new game. It does give you a warning but both times I wasn't paying attention and just clicked okay which reset the game. It mostly happens when I mess up a level and want to quickly restart the current level so I press without thinking due to muscle memory as in other games the start new game option usually just restarts the current level.

**Comment by ochadenas** [comment]
I see your point.  Will try to find a solution.

However, in version 1.20 there is a button that allows to replay a level without passing by the main menu. Perhaps that does already help to avoid the problem.

**Comment by ochadenas** [comment]
In version 1.29, the "New Game" button has been moved to the settings page.
