### ISSUE TITLE
Numbers touch target is too small for some phones.

### ISSUE THREAD

**Issue by capsicumw** [ochadenas/cpudefense#37]
v1.21
The tap-to-invert part of the game hardly works on my phone, the target size is simply way too small for average-sized male fingers. (It takes on the order of ten taps to trigger each inversion.)  
Maybe this game was intended for tablets, but that is not stated in the description on Fdroid.

Samsung S20fe, in good condition, recently factory reset, no added screen protector. Android 13(kernel 4.19.113) with "One UI" 5.1.
Size | 6.5 inches 165mm
Resolution | 1080 x 2400 pixels, 20:9 ratio (~407 ppi density)
I have tried turning on large buttons in-game settings with no effect on the gameplay. I then adjusted the phone's system-wide zoom testing min max and a middle setting, the game became just barely playable at maximum system zoom, but still not a pleasant experience. Moving Android system zoom from medium to high reduces the average number of taps per inversion from about ten to about four.

Maybe this could be a game setting, considering the wide range of phones and tablets on the market.

**Comment by ochadenas** [comment]
No, the game is not intended for tablets. The physical device I'm using for testing is even a little smaller than yours (it has only 720 x 1480, however).

In version 1.22, the tapping area should scale better with the screen density. And the "use large buttons" switch also enlarges the numbers. Just give it a try and tell me if it works better now.
