### ISSUE TITLE
Somewhere it says coins aren't affected by anything other than subtraction. 

### ISSUE THREAD

**Issue by ThisIsPaulDaily** [ochadenas/cpudefense#41]
This is a lie, I played level 21 with an entire course of subtract 7's with maxed out speed and range and the two tokens still got through. 

I replayed with just a level 6 shift register and a sub 3 and it took out the token. 

Not sure what level text it is that says only subtractions work on tokens, but it's wrong.

**Comment by ochadenas** [comment]
The coins are not affected by MEM and ACC, but they _are_ by SUB and SHR. This is in the introductory text to level 21.
