### ISSUE TITLE
assert a screen keep awake / option to keep awake

### ISSUE THREAD

**Issue by ThisIsPaulDaily** [ochadenas/cpudefense#42]
My screen timeout is 15 seconds and when the screen turns off, often the game stops and goes back to the level select. Several apps assert keeping the screen on. 

Also when rotating the screen from portrait to landscape the game goes back to level select and you lose progress and any tokens gathered during that level.

**Comment by ochadenas** [comment]
from version 1.23, the game won't switch to landscape mode. Also, it tries to keep the screen on.
