### ISSUE TITLE
I can't see the cost of an upgrade in the latest version. 

### ISSUE THREAD

**Issue by ThisIsPaulDaily** [ochadenas/cpudefense#43]
I'm using lineage OS with a Moto G7+ (Lake) 
It used to show some of the words cost and a number, but now I just have to spam buy and guess the cost. It could be that the upgrades cost equal to the level they are, which does feel a little grindy. 

Maybe the cost could be next to the buy button if you can't fit it in the portrait box.

**Comment by ochadenas** [comment]
The costs now show up when you long-press on a portrait.

**Comment by ochadenas** [comment]
> Maybe the cost could be next to the buy button if you can't fit it in the portrait box.

Good idea. Done in 1.23.
