### ISSUE TITLE
Rotating the screen restarts stage

### ISSUE THREAD

**Issue by juleskers** [ochadenas/cpudefense#45]
Hi again!

I've started a new round of CPU defense, since you seem to have been very busy with improvements ❤️

As I was retrying stage 8 today (still my nemesis..) I accidentally moved my phone enough to trigger a switch to landscape mode.
suddenly, I was back at the level intro text.

I could reproduce this: rotating tge phone to landscape goes directly from the middle of a wave, back to the text intro for the stage (black screen, where the words, then the "start game" +"heroes" buttons, fade in.

**Comment by ochadenas** [comment]
I'll have to investigate, but I know that this really is a problem. The thing is, Android treats a change of orientation basically as "kill  the app, and then restart it in landscape mode". It is left to the application to get back into the same state as before. This is always quite tricky and error-prone.

**Comment by ochadenas** [comment]
ok, simple solution: forbid change to landscape mode. The game doesn't look good in landscape anyway. 

Changed in version 1.23.
