### ISSUE TITLE
Better adaptive interface

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#53]
I'd have opened an issue for euch of these but i think they all fit in one encompassing issue.

There are quite a few instances in which i found that the in-game interface didn't account for longer text.
1. In level 15, the wave counter isn't fully displayed: 
![level15 stage](https://github.com/ochadenas/cpudefense/assets/80604512/8c3f768a-da69-46eb-aca3-334ca930def1)
2. I bet the original text fits in this right panel, but in the translated version, the text isn't entirely displayed.
![wrappingtexttranslate](https://github.com/ochadenas/cpudefense/assets/80604512/465a5810-df40-4926-bb9c-364563117b03)
3. In the about page, the title isn't correctly displayed.
![Screenshot_20231030-030700](https://github.com/ochadenas/cpudefense/assets/80604512/8765dcd8-ea48-4559-ad84-525a03be11e7)

I think these visual bugs are due to fixed values, and generally using placement rules that do not take variables lenghts of text or variable screen sizes into account. May be a bit long to go through and adapt to, but i think it will al be worth it in the end :)

**Comment by ochadenas** [comment]
The size of score board elements has been changed in 1.24 and again in 1.25. Hopefully this will look better then. 

The biography text should be scrollable, but that is for some future version.

The Settings screen layout has always been a problem. Perhaps it's better to have separate dialogs "settings" and "about".
