### ISSUE TITLE
Refund select recruit upgrades instead of full reset

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#54]
A full reset of the recruits is quite destructive regarding the strategy you put in place along the previous levels.
Being able to refund each level of recruit one by one would help manage these better between levels with drastically different layouts.

**Comment by ochadenas** [comment]
Well, originally the possibility to reset the heroes was created more or less for debugging purposes. I had no intention to leave it in the game ... I thought that once you have chosen a "career path", you'd stick to it, a bit as in RPG games. 

Only when I noticed that obviously many players actively used this possibility I decided that it should stay, as it gives room for more strategic thinking. But I'm not sure whether I like the idea to change the heroes before each level. Have to think about it.

**Comment by Cwpute** [comment]
Well from my experience, i've been *required* to reset the recruits every now and then, because at some point i chose to invest my coins in the wrong direction. If i were required to keep my recruits and only improve on them, i would have been stuck in many cases and required to restart the whole campaign… i would have probably let the game down.
So to me this feature is essential.

I like to redistribute my coins as it makes me think of the best strategy for this or that level.
That would also allow you to try more unique layouts designed for specific chip combinations and all ;)

**Comment by Kutabu** [comment]
@ochadenas 
If you want to keep the hero-reset feature, but also want to make it less attractive to change the heroes before each level, you can price the reset by the cost of 3 coins (=one level reward).

**Comment by vertigo220** [comment]
Personally, I was able to get several levels into endless mode without having to reset my heroes, getting perfect on every level, often even going a few levels at a time before doing any upgrades (and even then not because I needed to). So I certainly don't think it's necessary to do it every level, or even on a regular basis. And the only reason I did a reset was because I hit a sudden difficulty spike and wanted to remove coins from less useful heroes (mem chip speed/range, max hero level, unwanted chip count, starting information) to spend them on more useful ones. And now that I've done that, I don't imagine I'll want/need to do it again, at least for a while. But it would have been easier to be able to just refund those than having to do a full reset and re-upgrade all the others, not to mention that I accidentally upgraded the wrong one in the process and had to reset again.

**Comment by Urban-Hacker** [comment]
I think resetting everything is and should be part of the strategy. I would not add the ability to do partial refunds or partial reset. This forces the player to experiment with new things and also makes it fun.

If you can just "refund" a hero you will start micromanaging and only change a few variables. I think its good if when you are in the middle of a level you realize you forgot some important hero and have to start again. This is part of the re-playability and discovery process.

I also noticed the strategy even on the same level can vary a lot depending on which hero you choose.

**Comment by Cwpute** [comment]
I understand your point with micromanaging: you don't want players to optimize their hero upgrades, because you'd rather have them spend most of their time playing the actual game.
But since hero upgrades are already such an integral part of how you actually end up playing, and end up progressing through the levels, i feel hero upgrades could be given a bit more thought. But until then, we have what we have!

My initial suggestion was to allow players more control and understanding over the choices they make with the current hero upgrades, without having to reset the whole thing. Taking into account the learning process is good, but everybody learns differently, and being able to reset per hero allows you to tweak and favour one hero upgrade over another, and switch back easily without having to remember the whole thing.

If the level progression was dedicated to linearity and acted like a handcrafted campaign (like i suggest in #85 and #85) with  upgrades you commit to without being able to reset them, you could have certain points in the progression during which the game could force an upgrade reset, allowing you to think differently about how you should tackle the next level. This would be a great oppontunity for replayability and learning how upgrades work !

Le 8 mars 2024 10:45:24 GMT+01:00, Urban-Hacker ***@***.***> a écrit :

**Comment by vertigo220** [comment]
> I think resetting everything is and should be part of the strategy. I would not add the ability to do partial refunds or partial reset.

I'm not sure I see the point of allowing resets, not to mention having it be part of the strategy, but not allowing it to be done partially. If it's allowed fully but not partially, the same exact thing can be accomplished, only with taking more time, which benefits no one, not to mention the frustration of accidentally upgrading a hero too many times or upgrading the wrong hero, which I did once, and which then requires resetting and doing it all over again. Either there should be _no_ refunding (which I very much think would be the wrong approach, and even then there would _need_ to be an undo _while_ making changes, and they are only locked in once done) or it should allow doing it by increasing and decreasing each hero as needed.

And again, I say this as someone who made it several levels into turbo mode with a perfect on each level with only one reset. So personally I don't even think the game _requires_ doing it (unless you just screw up and do a poor job initially), but it's more a quality of life thing.

**Comment by ochadenas** [comment]
@vertigo220 : I see your point. As I said some months ago, originally the hero reset was not planned in the game, it was just a kind of help during development. But since then it has turn out to be a very popular feature. And it doesn't make sense to allow it, but only with lots of pain.

I'll try to find some space for a "fire" button ...

**Comment by ochadenas** [comment]
I've finally implemented this (in version 1.33). Heroes can now be downgraded individually, with the exception of Sid Meier.
