### ISSUE TITLE
More control over resuming pause

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#55]
Currently the pause is resumed when you tab anywhere on the scren… which renders the pause useless to me. Using the pause, i'd like to be able to move around the stage, assess the situation, and only for the game to resume when i choose so but, alas! i can't move around the stage as any tap on any part of the screen unpauses it.

In short i'd like the pause to only resume when i press the play button, not in any other situation.

**Comment by ochadenas** [comment]
Understood ;)
Changed in 1.25.
