### ISSUE TITLE
SHR chips of level 9 and above do nothing to attackers.

### ISSUE THREAD

**Issue by invinciblespeed** [ochadenas/cpudefense#56]
SHR chips of level 9 and above do not do anything. When an attacker interacts with the chip, an animation plays as if they are being shifted, but there is no change in their value.
This can be reproduced and observed by placing an SHR chip at the start of a stage and upgrading it to level 9, where attackers will simply pass over it without taking any damage.

**Comment by ochadenas** [comment]
You're right. Thanks for the report - I never had the idea that one would upgrade the chips up to these levels.

Fixed in 1.25. However, chip upgrades are limited to 12 now.
