### ISSUE TITLE
Large chip sell values do not get converted to B or KiB

### ISSUE THREAD

**Issue by invinciblespeed** [ochadenas/cpudefense#58]
![chipval](https://github.com/ochadenas/cpudefense/assets/43712584/9b8e9291-a02a-4bc4-92dd-013c3a580eea)
As seen here, large sell values are not converted to B or KiB when they exceed certain thresholds, even though chip upgrade values are converted.
This can be reproduced and observed by upgrading chips to very high levels.

**Comment by ochadenas** [comment]
That's quite a funny bug you've found. In fact, when selling chips the amount is _negative_. This means that the condition 
if (number < 512) 
is always true.

Fixed in 1.25.
