### ISSUE TITLE
Game does not resume if paused between waves

### ISSUE THREAD

**Issue by Kutabu** [ochadenas/cpudefense#59]
Game does not resume properly if paused between waves. The already spawend numbers continue moving, but no new numbers appear.

I assume this issue is caused by the stage delay-time. If the game is paused within this time, GamePhase changes to PAUSED and nextWave()-funtion will refuse to start by returing null.
I recommend to change the position of delay(3000L) before the first attaker of a wave spawns.

Game.kt line 333...
```kotlin
fun onEndOfWave()
    {
        currentWave = null
        GlobalScope.launch { delay(3000L); startNextWave() }
    }
``` 

and Stage.tk line 192...
```kotlin
fun nextWave(): Wave?
    {
        if (theGame.state.phase != Game.GamePhase.RUNNING)
            return null
        else if (waves.size == 0)
```

**Comment by Kutabu** [comment]
Okay, I found out that after leaving the stage wich _back_ the  "continueGameButton" on the main menu continues the game properly.

**Comment by ochadenas** [comment]
You're right. This may be the cause of several bug reports "no more attackers appear after level xy" which I was never able to reproduce.

Another problem is that the 3 seconds delay does not change when the game is accelerated.

**Comment by ochadenas** [comment]
Changed the whole mechanism of how delays are calculated.
