### ISSUE TITLE
Game unpaused after phone suspend

### ISSUE THREAD

**Issue by chrysn** [ochadenas/cpudefense#61]
When I run the game, pause it, suspend my Android device (Fairphone 5, Android 13) and wake it up, the game continues even though the play/pause icon shows it as paused. I have to press the button twice (presumably once to unpause, then to pause again) for the game to continue.

Other than #54 and this (and a small personal misgiving about the use of cryptocoins to hire the heroes of our trade, and frustration with turbo level 8 ;-) ), this is a great game -- thanks for developing and publishing it!

**Comment by ochadenas** [comment]
Should be fixed now (in version 1.27).

And thanks for your feedback!
