### ISSUE TITLE
[balance] You can use Meier + Schneier heroes to set all enemies to 0 and make it too easy

### ISSUE THREAD

**Issue by theseus-david** [ochadenas/cpudefense#62]
It's possible to upgrade Sid Meier to +3 and then have Bruce Schneier set attacker strength to 0.00, making all enemies 0, which means you just need a sub chip at the entry of every level to win... so you can beat turbo mode very quickly once you have enough coins to get Meier + Schneier.

Perhaps Schneier should have a minimum value of 0.2 or something?

(this bug report is actually from a 9 year old, my son and I are both loving this game)

**Comment by ochadenas** [comment]
You are right. Schneier at level 10 will multiply each attacker's value with 0.0 ... Have to think of a different formula.

Thanks & regards to your son!

**Comment by ochadenas** [comment]
Let's try with the function 2^(level_of_schneier / 2). That would change the factor as shown in the table:

level | old | new
---|---|---
0|1|1
1|0,9|0,71
2|0,8|0,5
3|0,7|0,35
4|0,6|0,25
5|0,5|0,18
6|0,4|0,13
7|0,3|0,09
8|0,2|0,06
9|0,1|0,04
10|0|0,03

**Comment by ochadenas** [comment]
had to modify this table again a bit, but in version 1.27 at least it is no longer possible to reduce the strength to 0.
