### ISSUE TITLE
Add affected chip name to range-upgrading recruits

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#65]
On the french version, the current only way to tell which chip's is being upgraded is by watching the recruit's coloured contour, but this is not visible when the recruit upgardes are reset (they become grey).
![Screenshot_20231206-141931](https://github.com/ochadenas/cpudefense/assets/80604512/fad8e569-cb8d-4f3a-925e-189d9fd1856e)
But this might be becaus the french translation is too long, and the name of the chip is sent to an hypothetical second line which isn't shown on screen.

Maybe account for these possible longer translated lines which might not be shown (here and in other places maybe).

**Comment by Cwpute** [comment]
May be related to #53

**Comment by ochadenas** [comment]
No, that has nothing to do with the French translation, it's a bug. The chip type has been forgotten in the text.

**Comment by ochadenas** [comment]
fixed in 1.27
