### ISSUE TITLE
Coin activate MEM chips

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#70]
… while coin aren't affected by MEM chips.
MEM chips are already underpowered, by if coins activate it preventr those chups to potentially catch another attacker right behind 😄

MEM chips shouldn't be activated by coins.

**Comment by ochadenas** [comment]
Se issue 67 ... I think that the only thing of preventing the combination ACC+MEM from winning every game is the fact that coins are immune to this.

**Comment by Cwpute** [comment]
(Referencing issue #67 for later)

I'm not asking for MEM chips to catch coins.
I'm saying that, since coins are not affected by MEM chips, these MEM chips shouldn't activate when a coin goes by them. Since they have quite a big cooldown, having a coin activate them without being affected means it essentialy doubles its cooldown timer, and potentially prevents them from eating an attacker that would be hugging the coin.

**Comment by ochadenas** [comment]
Ah, I see. That's a bug.

**Comment by ochadenas** [comment]
fixed in 1.27.
