### ISSUE TITLE
Translation contributions ?

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#72]
How should we do if we want to contribute translations to this project ?

Should we open issues for each typo or error we find ? or is there a tool we can use to suggest translations ?
I've used Crowdin and Weblate before and they work quite well. I've heard of Transifex too, but never used it.

**Comment by ochadenas** [comment]
Thanks a lot for proposing your help! I appreciate very much your interest in the project.

I have not much experience how to deal with translation contributions. I have no specific tool for translation, I just use the built-in editor in Android studio. This game is my first project on Github ... 

I think the easiest way is to do corrections directly in the strings.xml files (which are located under app/src/main/res/values-xxx) und push it via git. If I understand correctly, this will create a merge request, and I'll have to pull the changes into the main repo. Or, if you do not have git access, just download the file, edit it, and attach it to a comment.

Of course I would be interested in having translations other than English, French, or German ;) These are the only languages I speak sufficiently well to be able to start a translation, or to verify its correctness. I noticed that just putting a text through Google translate or Deepl often produces ... strange results.

**Comment by Cwpute** [comment]
Yeah machine translation has a very bad habit of using different words for the same thing sometimes. For precise wording like it's needed in games, it's far from usable.

I've had a Github account for a long time, supposedly to host my own game there… but it never happened. So i don't know much about git either.
What i know though is that using external tools like Crowdin or Weblate (or some kind of light parser like the dev of Snappymail uses) makes it easy to contribute on mobile (my most used device). If i had to `git pull` and `push` for a translation… well i don't even know if git is usable on mobile.

I may look into it some day though, because it's an itch i might give up to at some point, but don't take that as a promise 👀

**Comment by ochadenas** [comment]
I'm closing this issue to reduce the number of open ones ...

Feel free to add or correct/modify the translation files. Either through git, or just send the updated xml file.
