### ISSUE TITLE
Level number doesn't specifiy if Turbo or not

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#77]
The main menu level number doesn't say if the level reached is a turbo level or not.
It could just show `turbo` next to the level number, or have its own little logo, something like one of these maybe: `🎯`,`🔥`,`🚨` or`🚀` ?

**Comment by ochadenas** [comment]
Yes, it does! Normal levels are indicated in green, turbo ones in yellow, and the (yet to come) endless levels in red. That matches the colours used in the level selection dialog, and also the colour of the status LEDs within the levels.

**Comment by Cwpute** [comment]
Oooh that explains is… i am slightly colourblind and i didn't see the difference between the green and yellow. Didn't even realize there was a colour difference between the two.

As a rule of thumb, if you want you colours to be readable, use a set that features contrasted ones (that have a different shade of light or dark, regardless of their hue). And if you can't change the colours, combine a symbol witf it ;)

Le 16 janvier 2024 12:34:45 GMT+01:00, ochadenas ***@***.***> a écrit :

**Comment by ochadenas** [comment]
I'd like to close this issue. As @Kutabu mentioned (I had completely forgotten this), the series is shown when you tap on the level number on the welcome screen. In the latest version, the info is even correct ;)

I can't really imagine an icon there, and anyway, it is not really a crucially important info.
