### ISSUE TITLE
Chip upgrade-selling interface improvment

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#86]
When upgrading a chip you have to slightly move your finger to select the desired option beteween upgrading and selling. This is a small thing that is a bit unnecessary and takes more space than needed.
![qupgrade now](https://github.com/ochadenas/cpudefense/assets/80604512/a4c8dd90-1bd9-4050-b9a4-6a5d26ffb5ee)

You could have the upgrade button exactly superimpose the chip below so that you can simply douple tap the chip to upgrade it.
![qupgrade ex1](https://github.com/ochadenas/cpudefense/assets/80604512/6d2c20d8-dd86-4b31-be15-2f60e7c245ed)
On this example above i put the remaining sell buton right under the chip to better emphasize a little detail i added: less transparent button backgrounds. I thinks it adds to their visibility.
![qupgrade ex2](https://github.com/ochadenas/cpudefense/assets/80604512/de1d480b-8949-4107-854c-5e5fbe2358b1)
Finally a little test i made to further improve the clarity of these buttons, as they have the same size and color as negative chips. With that thick line the relation to the original chip is now very clear.

**Comment by ochadenas** [comment]
I have tried to put the +1 option directly onto the slot, but I find it less intuitive than the original version. I just don't expect it there.

Perhaps make this toggleable, so that the player can choose between different layouts.

**Comment by Cwpute** [comment]
You may be right…
Maybe my grievances with this interface come from somewhere else… we'll see.

Le 18 janvier 2024 18:13:13 GMT+01:00, ochadenas ***@***.***> a écrit :

**Comment by ochadenas** [comment]
Closing this issue for clean up ...

I still think that it is ok to move the finger a bit. It's even somewhat desirable, I think: If the Sell button is exactly on the chip itself, then it is rather easy to click on Sell by accident. Consider it a kind of safety issue ...
