### ISSUE TITLE
Chip buying interface test improvment

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#87]
I tried my hand at a different chip buying interfaces to see what would come of it. The followings are tests i made using image modifications.

The original interface:
![Screenshot_20240114-200321](https://github.com/ochadenas/cpudefense/assets/80604512/89a1d252-1830-4be6-b61c-8446581a0c59)

My tests:
With a maximum of 8 different chips or options unlocked:
![Neochip full](https://github.com/ochadenas/cpudefense/assets/80604512/8a0cdefd-67cd-4e65-903a-868b67758060)
I used my previous idea of #86 and added a cancel button right above the available chip placement spot so you can cancel this action right away with a tap on the same spot you previously tapped (basically chat happened before, but clearly visualized). I wanted the interface to contrast from the rest of the game and used again an idea from the previously-mentioned issue to have a thick line linking the chip spot and its menu.

I iterated on the idea to see its potential.
With only two chips unlocked:
![Neochip ministart](https://github.com/ochadenas/cpudefense/assets/80604512/cd366b22-e90b-4819-9fa9-b4bb9db09391)
With locked chips not appearing:
![Neochip partial](https://github.com/ochadenas/cpudefense/assets/80604512/0aef93d9-c4a7-4af4-8b7d-1fa2a53099ed)
With locked chips appearing as only shadows
![Neochip shadow](https://github.com/ochadenas/cpudefense/assets/80604512/986bd16a-a1c5-46c3-8ab5-ccff410c3e71)
With locked chips appearing as empty boxes:
![Neochip empty](https://github.com/ochadenas/cpudefense/assets/80604512/b007c8fa-7352-4282-8fa8-e062d5fd8444)

**Comment by Cwpute** [comment]
A second attempt using the previous test as a base:
![Neochip2 full](https://github.com/ochadenas/cpudefense/assets/80604512/31fad6f2-8c0b-44c0-884a-12834cc90125)
![Neochip2 partial](https://github.com/ochadenas/cpudefense/assets/80604512/1ecc1f5d-751a-4a8d-8fec-3f3c727f1bb8)
![Neochip2 empty](https://github.com/ochadenas/cpudefense/assets/80604512/785aee9a-bb41-422d-b3b8-5a2b94cfc057)
 I figured the previous test was too heavy on the eyes and could be improved upon. I still used the line for menues set aside to the chip, but opted for a semi-transparent background to link all the chip options together, that also covers chip upgrade costs.

**Comment by Cwpute** [comment]
My final test design is a variation over the previous one, with the semi-transparent background being limited to the actual button outer borders:
![Neochip3 full](https://github.com/ochadenas/cpudefense/assets/80604512/5f320e44-48d1-48a0-ab2b-c32590a59db8)
![Neochip3 partial](https://github.com/ochadenas/cpudefense/assets/80604512/34ba098b-2d38-41c5-b112-a30afe471b8f)
![Neochip3 empty](https://github.com/ochadenas/cpudefense/assets/80604512/975ccaf9-32da-4a91-bc5b-8e91f63d451c)

**Comment by ochadenas** [comment]
I have experimented with different layouts and possibilities, but I am not convinced.

The circular layout is great and saves space when it is directly around the slot to upgrade. However, if the slot is near the edge of the screen, the whole circle must be shifted to the inner side, as can be seen in your screen shots.  And then the distance from the slot to the farthest upgrade box is really big. Especially if - in the early levels - most of the boxes are empty. One could mirror the whole layout in these cases, but then the player would have to search for the required box even more than now.

But the black rectangle behind the boxes does improve readability. This looks quite nice, and maybe this already solves the problem. What do you think of this layout?

![Screenshot_20240223_221902](https://github.com/ochadenas/cpudefense/assets/103358290/23b6ea40-f10e-4c64-95da-722ea4c014a0)

**Comment by ochadenas** [comment]
Tried to make the pricing labels a bit clearer.

![Screenshot_20240224_093832](https://github.com/ochadenas/cpudefense/assets/103358290/ec395683-7dc2-411a-bbda-dc9c326c5687)

**Comment by Cwpute** [comment]
Would it be possible to move the camera around instead of moving the interface, so that there is always enough space for the circular menu ?

I can see it being a problem though, with players tapping while the screen scrolls, thus tapping on the incorrect menu item… but you could always prevent the game from registering taps while the screen is moving by itself… hmm 🤔
Sounds like a lot of work for not much improvment :/

Le 23 février 2024 22:28:17 GMT+01:00, ochadenas ***@***.***> a écrit :

**Comment by Cwpute** [comment]
The pricing label previews are already better than the current ones 👍

Le 24 février 2024 09:40:14 GMT+01:00, ochadenas ***@***.***> a écrit :

**Comment by ochadenas** [comment]
> Would it be possible to move the camera around instead of moving the interface

I think that the player woud not expect this, and that it would rather confuse them.

Have also tried to make these thick white lines that connect the upgrades in your drawings, but they were surprisingly hard to implement. I finally abandoned, they would require rewriting lots of code.

If it's ok for you, I'd like to close this issue. The interface is already clearer now than it used to be, thanks to your input. As you say, further effort will probably not be worth the improvement.

**Comment by Cwpute** [comment]
Yes, sure, go on !
I'm merely suggesting and whether these get transformed into actual implemented ideas is only up to you in the end ! Don't overwork yourself if you don't feel like the idea is worth it.

Le 9 mars 2024 23:52:05 GMT+01:00, ochadenas ***@***.***> a écrit :
