### ISSUE TITLE
Some unwanted chips unaffected by Kilby upgrades

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#88]
Some chips are special since they are coded in a level's properties: the first NOP in level 24, or the SHL and ADD chips in level 23 turbo for example. These chips are not affected by Kilby's upgrades…

This may not be a bug, but a feature instead, but it probably should be explained why these preset unwanted chips won't be removed by Kilby.

**Comment by ochadenas** [comment]
Yes, Kilby only removes the randomly added chips, but not those that are fixed part of the level design.

I wouldn't call this a feature. It's just that it was much simpler to program that way.

**Comment by ochadenas** [comment]
I'm closing this for the moment. Just call it a feature.
