### ISSUE TITLE
Attackers still dangerous during MEM animation

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#89]
It seems attackers can still interact with game elements during the shrinking animation that triggers after a MEM chip stored them.

![bruh](https://github.com/ochadenas/cpudefense/assets/80604512/b710c9a8-af70-400c-95b2-82fa92ad16b7)

With this setup and with faster fast-forward activated, attackers that were sucked up by the MEM chip on the middle lane could still reach and hurt the CPU even though they were just sucked up by the MEM chip, seemingly because the animation lasts long enough for them to reack the CPU.

Two possible ways of fixing this would be to either fast-forward the animation as the game is fast-forwarded itself, or stop the attackers dead in their dead once they are affected by a MEM chip (set their speed to 0).

**Comment by ochadenas** [comment]
You are right: The attacker is removed only when the animation is over. And the animation are not sped up by FF mode (for explosions, I think this is the right thing to do). I'll try your solutions.

**Comment by Cwpute** [comment]
With the new endless mode, this problem can be experienced a lot!
Even with regular fast-forward, some chips are so close together that 3 of them can get activated by the same shrinking attacker.

**Comment by ochadenas** [comment]
This should be fixed as a side-effect of issue #100.
