### ISSUE TITLE
Phantom attacker blocks some chip attacks

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#90]
I was mass-upgrading this SHR chip while super-fast-forwarding, when suddenly it stopped working properly.
![phantom attacker](https://github.com/ochadenas/cpudefense/assets/80604512/c508b44d-adab-4e00-8e10-7785a45219ed)
This chip started targeting a seemingly phantom attacker in front of it, amd wouldn't affect other attackers unless they were closer to its center.
While i was croping this screenshot i cam back, i found the game on pause and the chip had reverted its behavior to normal.

It might have been triggered by an unwanted tap on an attacker whil upgrading the SHR chip, or an unwanted long press or gesture that somehow bugged the chip to target a phantom attacker.Might have also been made possible by the super-fast-forward being enabled (faster fast-forward).

**Comment by Cwpute** [comment]
![rpro](https://github.com/ochadenas/cpudefense/assets/80604512/340492d4-abb9-4923-9492-d22dffd60ebb)
I could reproduce this behavior while faster-fast-forwarding and upgrading the same chip. Now the visualization of in-range ennemies seems to indicate one that isn't even on the lane!
It might be the chip mistaking the player's tap for an attacker maybe ? Also the chips for which it happened are level 9 and 10, and high level chips seem to have been problematic in some previous issues.

**Comment by VA1DER** [comment]
This is quite noticeable on ACC chips where they will stop working.  I can verify it's not due to a tap and it happens sometimes even in slow stages.

A workaround is to pause, switch to a different app or home screen, then switch back to the game.  All seized chips will be free.

**Comment by ochadenas** [comment]
I think this was related to a bug when switching between apps. Should no longer happen now; if it does, please reopen.
