### ISSUE TITLE
Feature Request: Detailed explanation of how to destroy the coins.

### ISSUE THREAD

**Issue by Haruld-VondeBjorn** [ochadenas/cpudefense#93]
I'm not sure how to destroy the coins before it hits the cpu. 

Great educational game by the way, thanks for making and releasing it. !

**Comment by ochadenas** [comment]
> I'm not sure how to destroy the coins before it hits the cpu.

Just like any other attacker: With SHR and SUB chips. Only that the coins tend to be a little stronger than the rest, so you'll perhaps need one or two additional chips.

> Great educational game by the way, thanks for making and releasing it. !

Thanks a lot!
