### ISSUE TITLE
More ways to make Endless levels difficult

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#95]
It seems the most prominent difficulty progression lever seems to be the attacker's stats: power, speed and spawn rate (and number of waves).
This could be improved upon to vary level generation and provide more ways to make levels more difficult and interesting as you progress in Endless mode !

Here is a list of gameplay elements that can be fine-tuned to make procedural levels more difficult.
I'll only provide ideas based on what's already present in the game, what's already been used in hand-made levels or what i have noticed generated in Endless mode:

1. Attacker spawn points: managing a single entry point is different from managing 3 or 5! they complexify chip placement and chip spot hierarchy.
2. Entry lanes into the CPU: same as with previously, different lanes accessing a single CPU also multiplies the number of chips needed to achieve the same damage output.
3. Number of CPUs: same as the two previous points…
4. Number of chip placement spots: as the levels get harder, you'll need more chips to efficiently dispatch the attackers, so reducing the number of spots inherently reduces the potential for defense ! the contrary is also true: more chip séots means easier levels.
5. Independant lanes: having independant lanes requires yet more ressources for dedicated chips.
6. Number of cryptocoins: cryptocoins can be realy hard to tackle if you use many MEM chips. I believe this is already randomly chosen, but it can provide a challenge is later levels if you have to manage let's say 3 different cryptocoins on 3 different lanes.
7. Alternate paths: if you generate alternative chip paths in your level (alternative ways attackers travel through lanes), this should also weigh in in the level's difficulty, as this creates unexpected attacker behavior that could throw the player off and require them to reconsider their strategy.
8. Branching lanes: a single lane separating into two lanes creates are more complex level, and increases its difficulty. Merging two lanes does so as well, but to a lesser degree (as you need to manage, buy and upgrade less chips for the same amount of attackers).
9. Lowest number of chips between a spawn point and a CPU: probably my most feared feature in a level is a lane only passing through 2 chips before reaching the CPU. This shortest possible path should probably be taken as the basis on which to build the rest of the level's difficulty.
10. Lane lenght: different from the previous point, as this is about the actual lenght of the paths, rather than the number of chips it contains. You can have a really long path with only two chips, that is manageable because you can tap on the attackers to reverse them, and a super short path with 3 chips that is harder to manage because you can't tap on them at all, and you have to rely on your chips efficiency rather than your own ability to react.

**Comment by Cwpute** [comment]
11. Wave diversity: diverse ways makes for a more difficult level you have to adapt to, while similar waves only test your current chip setup resistance.

**Comment by ochadenas** [comment]
Most of these points are already realized. There are multiple entry points, you can have more than one CPU, there are multiple and possible separate lanes, and so on.

However, these are random choices that are made during level generation. There is no real link to difficulty. So you can have a stage with two entry points and a really short path to the cpu on lower levels, and a stage with long ways and lots of nodes to place your chips on higher level. Again, the game is not really intelligent, and it doesn't "know" whether a stage layout is difficult or not.

The only thing that is reliably increasing in difficulty is the number and strength of waves.

An idea would be to increase the probability of short lanes and multiple entry/exit points with the stage.

**Comment by Cwpute** [comment]
> An idea would be to increase the probability of short lanes and multiple entry/exit points with the stage.

That's effectively what my suggestion is about ! Less a collection of things that could make a game difficult, i was trying to suggest alleviating these different things to build difficult levels.

What i'm suggesting is building a tool to evaluate the difficulty of a generated level.
You would be able to value a level's difficulty based on their "weight": each of my previously listed points would "weight" a certain value, according to the difficulty it potentialy creates in a level. And all these levels traits and quirks combined, recognized anl generated in a level, would total to a certain "weight" that would give a general idea of the whole level's difficulty.
This would allow you to procedurally generate levels that would be more difficult the bigger their "weight" is, thus being able to create a more progressive, and possibly varied, series of endless levels !

Le 25 février 2024 17:29:10 GMT+01:00, ochadenas ***@***.***> a écrit :
