### ISSUE TITLE
Maze-like levels in Endless mode are a bit boring

### ISSUE THREAD

**Issue by Cwpute** [ochadenas/cpudefense#96]
I couldn't wait for the Fdroid update so i grabbed the binaries here and had some runs through the generated levels :)

And…I have to be honest: it wasn't very interesting to play through 😬 but i'm sure it can be improved upon!

The main problem is: *all generated levels look and play the same*… they have a maze-like structure with long lanes crossing each other and unexpected backtracking paths, with a huge number of chip spots.
This was very funny in the beginning, and i tried to get my head around all this spaghetti circuit… this visual clutter all makes attacker spawn rate and path way harder to predict. So i tried to place down SUB SHR and ACC chips strategically, but frankly i quickly gave up because by the far the best and simplest way to go is to upgrade MEM chips to the max and place them everywhere in your level, occasionaly using an entry level CLK chip for security and some ACC chips in the beginnig to prevent overheating.

The currently generated levels could provide a good challenge if used correctly, i'm sure ! but instead their structure just anihilate most attempts at understanding and planning around the generated level.

I took the opportunity to suggest two possible improvments to make the Endless mode more enjoyable:
* #97 
* #95 

Hope this feedback is helpful !

**Comment by Cwpute** [comment]
For reference, here is a comparison of my procedurally generated level 1 and 29 of Endless mode:
![level 1](https://github.com/ochadenas/cpudefense/assets/80604512/459d78d8-e58c-426b-8fc8-9ac5f924a71b)
![level 29](https://github.com/ochadenas/cpudefense/assets/80604512/f76d579f-e48d-4eea-89f8-7f415b68567e)
Appart from the *e x t r e m e* 😎 difference in the number of waves, nothing really changed in the layout.

I ended up using a lot more ACC chips than before, with only a single MEM chip at the end of the lane to recover the last atackers. But it was always the same strategy, that just lasted longer as the Endless mode progressed.

**Comment by ochadenas** [comment]
Hi, sorry for my late reply, and thanks for testing!

I think you are right, the generated levels are not really satisfying. But I'm not sure how to create really good level layouts.

As a quick fix, one could avoid (or at least reduce) the paths going bottom-up. I thought that would make the levels more interesting, but it turns out that the opposite is the case. The whole level gets too labyrinthine and confusing.

I'll experiment a bit, and also try your other suggestions in issue #95. If you have any ideas what a "good" level design could be, please tell me ...

**Comment by ochadenas** [comment]
Version 1.29: Paths no longer go upwards. Or at least only locally. And I think you're right, it looks much better that way. Also the number of lanes now have an actual meaning (only in endless level, in the other series they are still purely decorative).

**Comment by Cwpute** [comment]
Fantastic, excited to see the result !

Le 20 février 2024 11:23:04 GMT+01:00, ochadenas ***@***.***> a écrit :
